version: '2'
services:
  lend:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-1"
        awslogs-group: "nearby-server"
        awslogs-stream-prefix: "prod"
    ports:
      - "8080:8080"